"use client"

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { polygonMumbai, polygon } from "wagmi/chains";
import { publicProvider } from "wagmi/providers/public";
import { InjectedConnector } from "wagmi/connectors/injected";
import { configureChains, createConfig, WagmiConfig } from "wagmi";
import {LensProvider, LensConfig, development, production} from '@lens-protocol/react-web'
import { bindings as wagmiBindings } from '@lens-protocol/wagmi';

import { ThirdwebProvider, useSigner, useWallet } from "@thirdweb-dev/react";

const { publicClient, webSocketPublicClient } = configureChains(
  [polygonMumbai, polygon],
  [publicProvider()]
);

const config = createConfig({
  autoConnect: true,
  publicClient,
  webSocketPublicClient,
  connectors: [
    new InjectedConnector({
      options: {
        shimDisconnect: false,
      },
    }),
  ],
});

const lensConfig: LensConfig = {
  bindings: wagmiBindings(),
  environment: development,
};

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <WagmiConfig config={config}>
      <ThirdwebProvider activeChain={'goerli'}>
        <LensProvider config={lensConfig}>
          <body className={inter.className}>{children}</body>
        </LensProvider>
        </ThirdwebProvider>
      </WagmiConfig>
    </html>
  )
}
